apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-app
spec:
  selector:
    matchLabels:
      app: time-machine
  replicas: 3
  template:
    metadata:
      labels:
        app: time-machine
    spec:
      containers:
        - name: time-app
          image: saul/app
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
            
