apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: minikube-tutorial
build:
  artifacts:
  - image: saul/geoblink
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - deployment.yaml
    - service.yaml
